### PR TITLE
[Typo] Add "all" to the sentence about Javascript

### PR DESCRIPTION
**Pull request by kuchikuu**
I assume the sentence should be
"Note that not all websites..."
Here is a quick pull to fix this so that it looks better.

### CODE REVIEW

**Comment by kuchikuu** [comment]
Wow great, sorry, I messed up. 
I should make this in a different branch. 

So, I corrected the typo, and later I wanted to make a Pull Request to enable/disable cookies with a mouse-click.
Unfortunately I pulled it in my main, thinking I can only submit latest commits.
Please do let me know how much of a problem is that that I made it all in a single branch.

If it's a problem and you want Typo/Cookies but not the other, please let me know and close this pull request.

**Comment by crossbowerbt** [comment]
Thanks, i'll review it as soon as possible 👍

**Comment by crossbowerbt** [comment]
Thank you very much @kuchikuu, indeed the possibility to enable and disable cookies is important.

I've added it in a slightly different manner: instead of configuring it in the compilation phase you can enable it at runtime using the tools menu or the dillorc config file.

Added to dev with commit: https://github.com/crossbowerbt/dillo-plus/commit/5eb80f496a131e36880587ed6fdd0273d5171f65

Also fixed the typo in the README.md file: https://github.com/crossbowerbt/dillo-plus/commit/371add51ea02ea08c80b447b4a743ce623d54f14

**Comment by crossbowerbt** [comment]
Closing the issue

**Pull request closed without merging**
